# Market turnover

## File path

```{r mto_path}
stock_ret_month_path <- "/Volumes/Samsung_T7/Research/Database/CSMAR/股票市场系列/股票市场交易/个股回报率/月个股回报率/TRD_Mnth1990-12 至 2023-03.txt"
```

## Monthly trading volume: All A shares

Bottom-up average with all a shares

```{r tv}
market_turnover_m_csmar <- fread(stock_ret_month_path, colClasses = c(Stkcd = "character")) %>% 
  setlowercolnames() %>% 
  .[markettype %in% c(1, 4, 16, 32)] %>% 
  .[, tradingmonth := ymd(paste0(trdmnt, "-01"))] %>% 
  .[, .(stkcd, tradingmonth, mclsprc, mnshrtrd, mnvaltrd, msmvosd)] %>% 
  .[, mnshrfloata := msmvosd * 1000 / mclsprc] %>% 
  .[, `:=`(turnover_1 = mnshrtrd / mnshrfloata, turnover_2 = mnvaltrd / (msmvosd * 1000))] %>% 
  na.omit() %>% 
  .[, lapply(.SD, function(x) weighted.mean(x,w = msmvosd)), .SDcols = c("turnover_1", "turnover_2"), tradingmonth] %>% 
  setorder(tradingmonth) %>% 
  .[, (c("turnover_12m_mean_backward_1", "turnover_12m_mean_backward_2")) := lapply(.SD, RcppRoll::roll_meanr, n = 12), .SDcols = c("turnover_1", "turnover_2")] %>% 
  .[, (c("turnover_12m_mean_forward_1", "turnover_12m_mean_forward_2")) := lapply(.SD, RcppRoll::roll_meanl, n = 12), .SDcols = c("turnover_1", "turnover_2")] %>% 
  .[, tradingmonth := ceiling_date(tradingmonth, "m") -days(1)] %>% 
  .[]

#< Write to the local database
dbWriteTable(conn_macro,
    "market_turnover_m_csmar",
    value = market_turnover_m_csmar,
    overwrite = TRUE
  )
```
